### ISSUE TITLE
Visual Studio Marketplace profile missing github repo information

### ISSUE THREAD

**Issue by bdiz** [gvekony/sv-1800-2012#1]
I was trying to find your repo on your marketplace page https://marketplace.visualstudio.com/items?itemName=gvekony.systemverilog-1800-2012 but it is not included on your extensions profile.

Thanks for this extension.

**Comment by gvekony** [comment]
> I was trying to find your repo on your marketplace page https://marketplace.visualstudio.com/items?itemName=gvekony.systemverilog-1800-2012 but it is not included on your extensions profile.
> 
> Thanks for this extension.

Thank you for pointing this out! I have added all necessary information to the extension now (life has been busy recently), and also set the keywords and tags correctly. I hope it will be fine from now on! :)
