### ISSUE TITLE
Syntax highliting missing for property declarations within for loops

### ISSUE THREAD

**Issue by jgancedo** [gvekony/sv-1800-2012#2]
When writing a "for generate" block which contains a property declaration in its body, the code relative to the property declaration is not highlighted:
![syntax_high_issue](https://user-images.githubusercontent.com/17992965/46806616-f45b2000-cd5f-11e8-8597-65d05a73c876.PNG)

**Comment by gvekony** [comment]
Thank you for pointing this out! 
As I am working on the verification side, I haven't created a code where a a generate block or genvar was properly used. I've fixed the issue, so properties from now on (1.0.13) shall be scoped correctly in begin-end blocks, and moved the scoping of genvar from generate-endgenerate to normal nettypes.
![image](https://user-images.githubusercontent.com/12802157/46855692-b95ef800-ce04-11e8-88a6-9e2dac246f1f.png)

**Comment by jgancedo** [comment]
Thanks for the super-quick fix!
