### ISSUE TITLE
Install at ssh workspace

### ISSUE THREAD

**Issue by GGuedesAB** [gvekony/sv-1800-2012#3]
Hi! I really like this extension, but I can't install it on my ssh workspace, which is the only way I have to use my college resources. Is there a plan to support ssh installation? Or maybe, am I missing something? This is what I see when I try to install the extension from the marketplace within my ssh:
![image](https://user-images.githubusercontent.com/36898632/108867589-1de51100-75d4-11eb-927e-c419d3f79dba.png)
Thanks!

**Comment by gvekony** [comment]
Hey! Thank you for bringing my attention to this matter! I've just added the required changes (1.0.27) to the extension and I've tested with a local node. (I was able to manage to install to a remote .vscode-server) Please let me know if it works for you! 
Take care,
G.

**Comment by GGuedesAB** [comment]
Hi! I was able to install it correctly at my remote machine with ssh!
Thank you so much!
